/**
 * Regenerate supabase/migrations/*_seed_express_challenges.sql from the legacy
 * Express catalog (scripts/_legacy/challenges.ts). Run after editing that file:
 *   npx tsx scripts/generate-challenges-sql.mts
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CHALLENGES } from './_legacy/challenges.ts'

const LEGACY_SEED_IDS = [
  'ch_sky_blue',
  'ch_green_leaf',
  'ch_door_handle',
  'ch_shoe_pair',
  'ch_street_sign',
  'ch_bicycle',
  'ch_coffee_cup',
  'ch_staircase',
  'ch_reflection',
  'ch_yellow_object',
  'ch_clock_face',
] as const

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function uniqueSlug(base: string, used: Set<string>): string {
  let slug = base
  let n = 2
  while (used.has(slug)) {
    slug = `${base}-${n}`
    n += 1
  }
  used.add(slug)
  return slug
}

function row(ch: (typeof CHALLENGES)[number], slug: string): string {
  const criteria = JSON.stringify(ch.criteria)
  return `(${[
    sqlString(ch.id),
    sqlString(slug),
    sqlString(ch.title),
    sqlString(ch.prompt),
    sqlString(ch.difficulty),
    String(ch.points),
    `${sqlString(criteria)}::jsonb`,
    ch.active ? 'true' : 'false',
  ].join(', ')})`
}

if (CHALLENGES.length !== 1000) {
  throw new Error(`expected 1000 challenges, got ${CHALLENGES.length}`)
}

const deactivateIds = [
  ...LEGACY_SEED_IDS.filter((id) => !CHALLENGES.some((c) => c.id === id)),
  'ch_free',
] as const

const usedSlugs = new Set<string>()

const chunks: string[] = []
const batchSize = 50
for (let i = 0; i < CHALLENGES.length; i += batchSize) {
  const batch = CHALLENGES.slice(i, i + batchSize)
  chunks.push(
    `insert into public.challenges (id, slug, title, prompt, difficulty, points, criteria, active) values\n${batch.map((ch) => row(ch, uniqueSlug(ch.slug, usedSlugs))).join(',\n')}\non conflict (id) do update set\n  slug = excluded.slug,\n  title = excluded.title,\n  prompt = excluded.prompt,\n  difficulty = excluded.difficulty,\n  points = excluded.points,\n  criteria = excluded.criteria,\n  active = excluded.active;`,
  )
}

const sql = `-- Express catalog (${CHALLENGES.length} challenges) — generated by scripts/generate-challenges-sql.mts
-- Source: scripts/_legacy/challenges.ts (from pre-Supabase server/src/challenges.ts)

${chunks.join('\n\n')}

update public.challenges
set active = false
where id in (${deactivateIds.map(sqlString).join(', ')});
`

const outPath = join(
  import.meta.dirname,
  '../supabase/migrations/20260723100000_seed_express_challenges.sql',
)
writeFileSync(outPath, sql)
console.log(`wrote ${CHALLENGES.length} challenges to ${outPath}`)
console.log(`deactivates ${deactivateIds.length} legacy v0 seed rows`)
